// Generated by aven-voice-protocol. Do not edit.

export type RequestId = string;

export type SessionId = string;

export type RouteId = string;

export type CandidateId = string;

export type SpeakerId = string;

export type TurnId = string;

export type ClientTurnKey = string;

export type DecimalU64 = string;

export type CommandMeta = { protocol_version: number, request_id: RequestId, };

export type VoiceFeature = "input" | "output";

export type ConversationMode = "conversation";

export type VoicePrepareRequest = { features: Array<VoiceFeature>, protocol_version: number, request_id: RequestId, };

export type VoiceSessionStartRequest = { mode: ConversationMode, preferred_input: string | null, preferred_output: string | null, protocol_version: number, request_id: RequestId, };

export type VoiceSessionStopRequest = { session_id: SessionId, protocol_version: number, request_id: RequestId, };

export type VoiceSpeechBeginRequest = { session_id: SessionId, client_turn_key: ClientTurnKey | null, language: string, voice: string, protocol_version: number, request_id: RequestId, };

export type VoiceSpeechEnqueueRequest = { session_id: SessionId, turn_id: TurnId, segment_index: number, text: string, protocol_version: number, request_id: RequestId, };

export type VoiceSpeechFinishRequest = { session_id: SessionId, turn_id: TurnId, protocol_version: number, request_id: RequestId, };

export type SpeechCancelReason = "barge_in" | "manual" | "muted" | "session_stopped" | "superseded" | "route_fault";

export type VoiceSpeechCancelRequest = { session_id: SessionId, turn_id: TurnId | null, reason: SpeechCancelReason, protocol_version: number, request_id: RequestId, };

export type InputResetReason = "conversation_cleared" | "manual" | "model_recovery";

export type VoiceInputResetRequest = { session_id: SessionId, reason: InputResetReason, protocol_version: number, request_id: RequestId, };

export type VoiceSnapshotRequest = { session_id: SessionId | null, protocol_version: number, request_id: RequestId, };

export type VoiceDiagnosticsSubscribeRequest = { session_id: SessionId, enabled: boolean, protocol_version: number, request_id: RequestId, };

export type RuntimeStatus = "dormant" | "preparing" | "ready" | "failed";

export type SessionStatus = "closed" | "opening" | "active" | "suspended" | "recovering";

export type CaptureStatus = "closed" | "starting" | "live" | "denied" | "failed";

export type PlaybackStatus = "silent" | "synthesizing" | "buffered" | "playing" | "fading" | "failed";

export type UtteranceStatus = "idle" | "candidate" | "confirmed" | "finalizing";

export type EchoStatus = "bypassed" | "adapting" | "converged" | "degraded";

export type WorkerStatus = "sleeping" | "processing" | "cancelling" | "failed";

export type PreparationSnapshot = { runtime: RuntimeStatus, input_ready: boolean, output_ready: boolean, };

export type VoiceSessionStarted = { session_id: SessionId, snapshot: VoiceSnapshot, };

export type SpeechTurnStarted = { turn_id: TurnId, pending_segment_capacity: number, };

export type EnqueueResult = { accepted: boolean, idempotent: boolean, remaining_segment_capacity: number, };

export type SpeakerAttribution = { speaker_id: SpeakerId,
/**
 * Cosine-based model confidence in the range 0..=1. A newly created
 * anonymous cluster starts at 1 because no competing identity exists yet.
 */
confidence: number, };

export type VoiceSnapshot = { runtime: RuntimeStatus, session: SessionSnapshot, route: RouteSnapshot | null, capture: CaptureSnapshot, echo: EchoSnapshot, utterance: UtteranceSnapshot, recognizer: WorkerSnapshot, synthesis: SynthesisSnapshot, playback: PlaybackSnapshot, queues: Array<QueueSnapshot>, workers: Array<NamedWorkerSnapshot>, recent_errors: Array<VoiceError>, };

export type SessionSnapshot = { status: SessionStatus, session_id: SessionId | null, };

export type TimestampQuality = "hardware" | "host_estimated" | "callback_only";

export type RouteSnapshot = { route_id: RouteId, generation: DecimalU64, input_rate_hz: number, input_channels: number, output_rate_hz: number, output_channels: number, input_callback_frames: number | null, output_callback_frames: number | null, input_timestamp_quality: TimestampQuality, output_timestamp_quality: TimestampQuality, full_duplex_barge_in: boolean, };

export type CaptureSnapshot = { status: CaptureStatus, callback_age_ms: number | null, overruns: DecimalU64, };

export type EchoSnapshot = { status: EchoStatus, delay_hint_ms: number | null, drift_correction_ppm: number, render_rms: number, render_peak: number, raw_rms: number, raw_peak: number, clean_rms: number, clean_peak: number, clipped_fraction: number, echo_return_loss_db: number | null, echo_return_loss_enhancement_db: number | null, residual_echo_likelihood: number | null, reference_overruns: DecimalU64, };

export type UtteranceSnapshot = { status: UtteranceStatus, candidate_id: CandidateId | null, vad_probability: number, partial: string, };

export type WorkerSnapshot = { status: WorkerStatus, last_duration_ms: number | null, };

export type SynthesisSnapshot = { worker: WorkerSnapshot, turn_id: TurnId | null, segment_index: number | null, };

export type PlaybackSnapshot = { status: PlaybackStatus, speaking: boolean, queued_seconds: number, buffered_seconds: number, underruns: DecimalU64, };

export type QueueSnapshot = { name: string, fill: number, capacity: number, milliseconds: number | null, };

export type NamedWorkerSnapshot = { name: string, status: WorkerStatus, };

export type ErrorSeverity = "info" | "warning" | "error" | "fatal";

export type VoiceErrorCode = "permission_denied" | "environment_unavailable" | "no_input_device" | "no_output_device" | "route_open_failed" | "route_invalidated" | "callbacks_stalled" | "unsupported_format" | "capture_overrun" | "render_underrun" | "reference_overrun" | "clock_unstable" | "echo_failed" | "echo_not_converged" | "model_not_prepared" | "asr_failed" | "tts_failed" | "queue_full" | "invalid_text" | "segment_out_of_order" | "segment_conflict" | "stale_session" | "stale_turn" | "stale_route" | "request_conflict" | "protocol_mismatch" | "internal";

export type VoiceError = { code: VoiceErrorCode, severity: ErrorSeverity, retryable: boolean, session_id: SessionId | null, turn_id: TurnId | null, candidate_id: CandidateId | null, message: string, };

export type InputDiscardReason = "empty" | "unsafe_echo" | "reset" | "stale" | "overflow" | "route_changed" | "model_failed";

export type VoiceEvent = { "type": "status.runtime", status: RuntimeStatus, } | { "type": "status.session", status: SessionStatus, } | { "type": "status.route", route: RouteSnapshot | null, } | { "type": "status.capture", status: CaptureStatus, } | { "type": "status.echo", status: EchoStatus, full_duplex_barge_in: boolean, } | { "type": "input.candidate_started", candidate_id: CandidateId, far_end_active: boolean, } | { "type": "input.partial", candidate_id: CandidateId, text: string, } | { "type": "input.confirmed", candidate_id: CandidateId, barge_in_started: boolean, } | { "type": "input.speaker_identified", candidate_id: CandidateId, speaker: SpeakerAttribution, } | { "type": "input.final", candidate_id: CandidateId, text: string, } | { "type": "input.discarded", candidate_id: CandidateId, reason: InputDiscardReason, } | { "type": "playback.turn_started", turn_id: TurnId, } | { "type": "playback.segment_accepted", turn_id: TurnId, segment_index: number, } | { "type": "playback.synthesis_started", turn_id: TurnId, segment_index: number, } | { "type": "playback.synthesis_completed", turn_id: TurnId, segment_index: number, } | { "type": "playback.started", turn_id: TurnId, } | { "type": "playback.fading", turn_id: TurnId, duration_ms: number, } | { "type": "playback.completed", turn_id: TurnId, } | { "type": "playback.cancelled", turn_id: TurnId, reason: SpeechCancelReason, } | { "type": "playback.failed", turn_id: TurnId, error: VoiceError, } | { "type": "capacity.changed", pending_segments: number, synthesized_lead_ms: number, } | { "type": "diagnostics.snapshot", snapshot: VoiceSnapshot, } | { "type": "error.raised", error: VoiceError, };

export type VoiceEventEnvelope = { protocol_version: number, sequence: DecimalU64, session_id: SessionId | null, route_generation: DecimalU64 | null, at_mono_ms: number, event: VoiceEvent, };
